### ISSUE TITLE
crash 1.0.5

### ISSUE THREAD

**Issue by w5860363** [evolzmc/herbocraft#22]
entity_herbocraft_wither_turret

java.lang.NullPointerException: Ticking block entity
	at com.redblueflame.herbocraft.blocks.SterilizerBlockEntity.isAccepted(SterilizerBlockEntity.java:72)
	at com.redblueflame.herbocraft.blocks.SterilizerBlockEntity.checkWork(SterilizerBlockEntity.java:36)
	at com.redblueflame.herbocraft.blocks.AbstractProgressBlockEntity.method_16896(AbstractProgressBlockEntity.java:42)
	at net.minecraft.class_1937.method_18471(class_1937.java:552)
	at net.minecraft.class_3218.method_18765(class_3218.java:423)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Unknown Source)

**Comment by w5860363** [comment]
Use sterilizer to put wither_seed

**Comment by Redblueflame** [comment]
Oh sorry ! I'll fix this one in the next version
